// Generated by https://quicktype.io

export interface AlertaNew {
    ok:     boolean;
    alerta: Alerta[];
}

export interface AlertaNewInd {
    ok:     boolean;
    alerta: Alerta;
}

export interface Alerta {
    id:          number;
    personal:    string;
    descripcion: string;
    status:      number;
    fecha:       string;
    hora:        string;
    idUsuario:   number | null;
    idArea:      number;
    user:        User | null;
    area:        Area;
}

export interface Area {
    title: string;
    id:    number;
}

export interface User {
    name:     string;
    lastname: string;
    id:       number;
    celular?:string;
    dni?:string
}
