
// Generated by https://quicktype.io
export interface ResultAlertas {
    ok:     boolean;
    msg?:    string;
    alerta: Alerta[];
}

export interface ResultAlerta {
    ok:     boolean;
    msg?:    string;
    alerta: Alerta;
}

export interface Alerta {
    personal?:    string;
    area:        string;
    descripcion: string;
    estado?:      boolean;
    _id?:         string;
}

// Generated by https://quicktype.io

