// Generated by https://quicktype.io

export interface ResultAreas {
    ok:   boolean;
    area: Area[];
}
export interface ResultAreasInd {
    ok:   boolean;
    area: Area;
}
export interface Area {
    id:        number;
    title:     string;
    active:    number;
    createdAt: string;
    updatedAt: string;
}
