// Generated by https://quicktype.io

export interface ResultDni {
    ok:   boolean;
    data: Data;
}

export interface Data {
    nombreCompleto: string;
    documento:      string;
    direccion:      string;
    apellido:       string;
    nombre:         string;
}
