// Generated by https://quicktype.io

export interface ResultRol {
    ok:  boolean;
    rol: Rol[];
}

export interface Rol {
    id:        number;
    role:      string;
    active:    number;
    createdAt: string;
    updatedAt: string;
}
