// Generated by https://quicktype.io

export interface ResultSemanas {
    ok:      boolean;
    semanas: Semana[];
}

export interface Semana {
    id:     number;
    nombre: string;
    codigo: string;
}
